"""Every rules table on one page and one canvas, as live heading embeds.

    py -3.13 scripts/build_lens.py

Writes two lenses into the vault, both pointing at the REAL tables:

    Rules System/_Tables Lens.md        every table, grouped, in one page
    Rules System/_Tables Lens.canvas    the same, as cards you can arrange

Nothing is copied and no rules note is modified. Each entry is
`![[Note#Heading]]`, so the table you see IS the table in the note — and with
the Sync Embeds plugin enabled those embeds become editable in place and write
straight back to the source. That is the whole point: one copy, no sync step.

Heading embeds rather than block embeds (`#^anchor`) because Sync Embeds
addresses by heading. A handful of sections hold more than one table, so those
cards show every table under that heading; that is a display quirk, not a
correctness problem, and it avoids editing the rules notes to add anchors.
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VAULT = os.path.join(os.path.expanduser("~"), "Documents", "Obsidian Vault", "Settlements")
RULES = os.path.join(VAULT, "Rules System")

BANDS = [
    ("Core engine", ["Rules Engine", "Core Game Format", "Initiative & Activation"]),
    ("Combat", ["Shooting", "Melee", "Damage", "Morale", "Conditions"]),
    ("Gear", ["Weapons", "Deployables"]),
    ("Movement · terrain · machines",
     ["Movement", "Terrain", "Terrain Interaction", "Infrastructure", "Hacking"]),
    ("Crew", ["Unit Design", "List Building", "Progression", "Skill Paths"]),
    ("Campaign & settlement",
     ["Campaign", "Downtime", "Economy", "Settlement", "Structures", "Territory",
      "Events", "Scenarios", "Factions"]),
    ("Physical", ["Board Representation"]),
]


def tables_by_heading(note):
    """(heading, rows, shares) for every table, keyed by its enclosing heading.

    `shares` flags a heading that holds more than one table — the embed will
    show all of them, which is worth saying out loud on the card.
    """
    path = os.path.join(RULES, note + ".md")
    if not os.path.exists(path):
        return []
    lines = io.open(path, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
    found, heading = [], None
    i = 0
    while i < len(lines):
        bare = re.sub(r"^>\s?", "", lines[i])
        h = re.match(r"^(#{2,4})\s+(.*)", lines[i])   # NOT bare: callout headings
        if h:                                          # are not link targets
            heading = h.group(2).strip()
            i += 1
            continue
        nxt = re.sub(r"^>\s?", "", lines[i + 1]) if i + 1 < len(lines) else ""
        if bare.startswith("|") and re.match(r"^\|[\s:|-]+\|?$", nxt):
            j, n = i + 2, 0
            while j < len(lines) and re.sub(r"^>\s?", "", lines[j]).startswith("|"):
                n += 1
                j += 1
            if n and heading:
                found.append([heading, n])
            i = j
            continue
        i += 1

    # collapse repeats and mark the shared headings
    out, seen = [], {}
    for hd, n in found:
        if hd in seen:
            out[seen[hd]][1] += n
            out[seen[hd]][2] = True
        else:
            seen[hd] = len(out)
            out.append([hd, n, False])
    return out


def clean(h):
    """A heading as it must be written inside a wikilink target."""
    h = re.sub(r"[*`]", "", h)
    h = re.sub(r"\[\[([^\]|]*\|)?([^\]]+)\]\]", r"\2", h)
    return h.replace("#", "").replace("|", "").strip()


def collect():
    bands = []
    for band, notes in BANDS:
        items = []
        for note in notes:
            for hd, rows, shares in tables_by_heading(note):
                items.append((note, clean(hd), rows, shares))
        if items:
            bands.append((band, items))
    return bands


def write_page(bands):
    n_t = sum(len(i) for _, i in bands)
    n_r = sum(r for _, i in bands for _, _, r, _ in i)
    out = [
        "---", "type: catalogue", "title: Tables Lens",
        "tags: [settlements/catalogue]", "---",
        "# 🪟 Tables Lens — every table, live",
        "",
        "> [!success] These are the real tables, not copies",
        "> Every table below is a live embed of its section in the source note, so "
        "editing the note updates this page instantly.",
        "> ",
        "> **With the [Sync Embeds] plugin enabled you can edit them right here** and "
        "the change is written back into the source note. One copy, no sync step, "
        "nothing to drift.",
        "> ",
        "> Generated by `scripts/build_lens.py`. Re-run it after adding a table.",
        "",
        "*%d tables · %d rows · %d notes*" % (n_t, n_r, sum(len(x[1]) for x in BANDS)),
        "",
    ]
    for band, items in bands:
        out += ["---", "", "## " + band, ""]
        for note, hd, rows, shares in items:
            note_hd = "%s — %s" % (note, hd)
            out += ["### " + note_hd,
                    "*[[%s]] · %d rows%s*" % (note, rows,
                                              " · shares this heading with another table" if shares else ""),
                    "",
                    "![[%s#%s]]" % (note, hd),
                    ""]
    p = os.path.join(RULES, "_Tables Lens.md")
    io.open(p, "w", encoding="utf-8", newline="").write("\n".join(out) + "\n")
    return p, n_t, n_r


CARD_W, GAP, PAD, ROW_PX, HEAD_PX = 520, 40, 60, 26, 110
MAX_H = 1200


def write_canvas(bands):
    nodes, y, k = [], 0, 0
    for band, items in bands:
        cols = min(len(items), 5)
        rows_n = (len(items) + cols - 1) // cols
        h = min(MAX_H, HEAD_PX + max(r for _, _, r, _ in items) * ROW_PX)
        gw = cols * CARD_W + (cols - 1) * GAP + PAD * 2
        gh = rows_n * h + (rows_n - 1) * GAP + PAD * 2 + 20
        k += 1
        nodes.append({"id": "g%d" % k, "type": "group", "label": band,
                      "x": 0, "y": y, "width": gw, "height": gh})
        for idx, (note, hd, rows, shares) in enumerate(items):
            k += 1
            nodes.append({
                "id": "n%d" % k, "type": "text",
                "text": "![[%s#%s]]" % (note, hd),
                "x": PAD + (idx % cols) * (CARD_W + GAP),
                "y": y + PAD + 20 + (idx // cols) * (h + GAP),
                "width": CARD_W,
                "height": min(MAX_H, HEAD_PX + rows * ROW_PX)})
        y += gh + GAP * 2
    p = os.path.join(RULES, "_Tables Lens.canvas")
    io.open(p, "w", encoding="utf-8", newline="").write(
        json.dumps({"nodes": nodes, "edges": []}, indent=1, ensure_ascii=False))
    return p, len([n for n in nodes if n["type"] == "text"])


def headings_of(note):
    p = os.path.join(RULES, note + ".md")
    if not os.path.exists(p):
        return set()
    txt = io.open(p, encoding="utf-8").read()
    return {clean(m.group(1)) for m in re.finditer(r"^#{1,6}\s+(.*)$", txt, re.M)}


def check(bands):
    """Refuse to ship a lens whose embeds do not resolve."""
    cache, bad = {}, []
    for _, items in bands:
        for note, hd, _, _ in items:
            if note not in cache:
                cache[note] = headings_of(note)
            if hd not in cache[note]:
                bad.append((note, hd))
    return bad


if __name__ == "__main__":
    bands = collect()
    broken = check(bands)
    if broken:
        print("%d embed target(s) do not resolve — NOT writing the lens:" % len(broken))
        for n, h in broken:
            print("   %s # %s" % (n, h))
        sys.exit(1)
    p1, n_t, n_r = write_page(bands)
    p2, n_c = write_canvas(bands)
    print("wrote %s" % p1)
    print("      %d tables, %d rows, %d bands" % (n_t, n_r, len(bands)))
    print("wrote %s" % p2)
    print("      %d embed cards" % n_c)
    shared = [(n, h) for _, i in bands for n, h, _, s in i if s]
    if shared:
        print("\n%d headings hold more than one table — those cards show all of them:"
              % len(shared))
        for n, h in shared[:6]:
            print("   %s — %s" % (n, h))
